
spring:
    main:
        allow-bean-definition-overriding: true
        web-application-type: reactive
    application:
        name: rootapp
    data:
        mongodb:
            uri: mongodb://root:root@223.130.153.131:27017/mydb?retryWrites=true&w=majority&authSource=admin
    sql:
        init:
            mode: always
            encoding: UTF-8
# logging:X
#     level:
#         org:
#             hibernate:
#                 SQL: debug
#                 type: trace
#         com:
#             example:
#                 demo:
#                     type: info

jwt:
    secret: bitc123231231mpbitcam565676qweweqpbitcam65757camp
    expiration: 
        access: 600000
        refresh: 1200000


server:
  port : 8888